[package]
name = "process-tx"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0"
csv = "1.3.0"
predicates = "3.1.2"
serde = { version = "1.0.214", features = ["derive"] }
thiserror = "1.0.66"
